version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8080"
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - uploads:/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  uploads:

networks:
  app-network:
    driver: bridge