import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Freelancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className="bg-color6" dir="rtl"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
