spring:
  datasource:
    url: jdbc:postgresql://45.159.150.47:5432/deadlinee
    username: freelancer
    password: 13521380Mm$$#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: deadlineefl@gmail.com
    password: chxihcpykqipbjdz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: backend
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.security: INFO
    com.manage.freelancer: INFO

app:
  upload:
    dir: /app/uploads/profile-images/

admin:
  email: mahdikargar.com@gmail.com